services:
  web:
    build: .
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=tOyfpIWf6zPCOw1RSVcu
      - DB_NAME=stacked-n-jacked-mvp
      - DB_PORT=5432
      - DB_HOST=db
      - SECRET_KEY=8fd5b5a225025b69ec13bb682981546acf8019c9ec2d457bdddd9082a722b001
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      expose:
        - 5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=tOyfpIWf6zPCOw1RSVcu
        - POSTGRES_DB=stacked-n-jacked-mvp

volumes:
      postgres_data: